version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
    - "8080:80"
    links:
    - redis
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
